In [3]:
import pandas as pd
import numpy as np

from Solar.regression.process_smhi import process_smhi

smhi_filename = "../data/smhi_Gi_Jan01-2026-May31-2026.txt"

X_smhi_2026, raw_smhi_2026 = process_smhi(smhi_filename)
X_smhi_2026

      G(i)  hour_sin  hour_cos   day_sin   day_cos
0      0.0  0.000000  1.000000  0.017213  0.999852
1      0.0  0.258819  0.965926  0.017213  0.999852
2      0.0  0.500000  0.866025  0.017213  0.999852
3      0.0  0.707107  0.707107  0.017213  0.999852
4      0.0  0.866025  0.500000  0.017213  0.999852
...    ...       ...       ...       ...       ...
3619  31.5 -0.965926  0.258819  0.516062 -0.856551
3620   0.0 -0.866025  0.500000  0.516062 -0.856551
3621   0.0 -0.707107  0.707107  0.516062 -0.856551
3622   0.0 -0.500000  0.866025  0.516062 -0.856551
3623   0.0 -0.258819  0.965926  0.516062 -0.856551

[3624 rows x 5 columns]

In [4]:
raw_smhi_2026

        YY  MM  DD  TT  G(i)            datetime
0     2026   1   1   0   0.0 2026-01-01 00:00:00
1     2026   1   1   1   0.0 2026-01-01 01:00:00
2     2026   1   1   2   0.0 2026-01-01 02:00:00
3     2026   1   1   3   0.0 2026-01-01 03:00:00
4     2026   1   1   4   0.0 2026-01-01 04:00:00
...    ...  ..  ..  ..   ...                 ...
3619  2026   5  31  19  31.5 2026-05-31 19:00:00
3620  2026   5  31  20   0.0 2026-05-31 20:00:00
3621  2026   5  31  21   0.0 2026-05-31 21:00:00
3622  2026   5  31  22   0.0 2026-05-31 22:00:00
3623  2026   5  31  23   0.0 2026-05-31 23:00:00

[3624 rows x 6 columns]

In [10]:
import joblib

fitted_gb_reg = joblib.load('../models/fitted_gb_reg.joblib')

In [11]:
smhi_2026_pred = fitted_gb_reg.predict(X_smhi_2026)

for line in smhi_2026_pred:
    print(line)

0.00937618331141725
0.00937618331141725
0.00937618331141725
0.009652763150173549
0.013546560582278645
0.01345677732074645
0.011689211680235862
0.013457149461220109
0.013548970245162318
8.576952685432198
19.837195595526676
22.703866423956633
17.282033735281853
5.153803518554511
0.010605926853328184
0.01060312737938799
0.009375612165499245
0.009376555451847832
0.009376181631921596
0.009376183311374617
0.009376183311403039
0.00937618331139238
0.00937618331139238
0.00937618331139238
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.013277488478206815
8.930737748713662
20.39503595022456
24.316548449494157
18.309821793088773
5.711390301944506
0.010334445086372681
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.017993078838488125
9.284191161698372
49.190324813145196
23.757311765485742
18.29462014331584
5.712658036756658
0.010334445086372681
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.013264443342723867
9.944825030758563
21.03137553630198
25.005071560263247
19.789579210263916
6.412915485710392
0.010334445086585844
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
1.9629231273695928
31.912411455180738
54.01155814919518
28.64029044908672
46.08041926345013
7.866025895339253
0.010333979402907891
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.7066589337398784
19.819549135686717
50.85390498631686
28.63984994844563
18.66885837045247
8.529947564870254
0.010332238148254982
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.705972432338951
11.946734564955152
48.62790379255121
29.242952014281045
22.273055086994653
8.54466644027835
0.010334634330474293
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.01377710150601636
11.160082509122415
23.75396650979804
55.53092936273054
26.94200896835895
22.242478721422433
0.010326989460552296
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
0.018598733632034365
12.492579377745534
29.124815025631587
68.46985169259635
50.742420359585054
10.116791420955561
0.010334634330474293
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
5.1970946303472285
55.71968289906522
100.02527235161422
114.27215914705988
86.37039615559827
38.672566733597336
1.1121595663540051
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
4.044155116650709
51.86193291523041
89.49325368680387
65.3800050524821
48.49270462099411
15.931169577230124
0.01566130998428999
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.009104701544461746
0.009104701544461746
0.009104701544461746
0.009381281383218046
0.013275078815323142
0.013185295553790947
0.011417729913280363
0.013185667694264606
3.7306422732493645
45.265882899581044
96.39223933725452
112.03359996523672
54.79536614249277
14.252390855470756
0.010877209937561725
0.010331645612432487
0.009104130398543742
0.009105073684892329
0.009104699864966093
0.009104701544419114
0.009104701544447535
0.009104701544436877
0.009104701544436877
0.009104701544436877
0.008969063463729488
0.008969063463729488
0.008969063463729488
0.009245643302485788
0.013139440734590883
0.0387186967498552
0.03695113110934462
0.03871906889032886
0.30179823567356584
13.960258836403076
27.145765372995278
31.820913587656367
26.469460031472845
12.406619128247806
0.009724382140344559
0.010196007531700229
0.008968492317811484
0.011958928581293486
0.01195855476136725
0.011958556440820271
0.008969063463715277
0.00896906346370462
0.00896906346370462
0.00896906346370462
0.008969063463729488
0.008969063463729488
0.008969063463729488
0.009245643302485788
0.013139440734590883
0.0387186967498552
0.03695113110934462
0.03871906889032886
0.3899970231936503
13.965873595612724
27.89749480303761
32.505192871398954
27.180862373603567
12.472389881201918
0.007211789168410088
0.010196007531700229
0.008968492317811484
0.011958928581293486
0.01195855476136725
0.011958556440820271
0.008969063463715277
0.00896906346370462
0.00896906346370462
0.00896906346370462
0.008969063463729488
0.008969063463729488
0.008969063463729488
0.009245643302485788
0.013139440734590883
0.0387186967498552
0.03695113110934462
0.03871906889032886
3.24959552013838
29.582077477868832
29.61805641163585
33.44882128676707
29.196225203801248
13.46315119113347
0.015525671903557732
0.010196007531700229
0.008968492317811484
0.011958928581293486
0.01195855476136725
0.011958556440820271
0.008969063463715277
0.00896906346370462
0.00896906346370462
0.00896906346370462
0.008969063463729488
0.008969063463729488
0.008969063463729488
0.009245643302485788
0.013139440734590883
0.0387186967498552
0.03695113110934462
0.03871906889032886
0.7605835758546529
14.510779779623158
27.97116456278581
32.0849161686132
26.99420140183115
13.46315119113347
0.06593093715482153
0.010196007531700229
0.008968492317811484
0.011958928581293486
0.01195855476136725
0.011958556440820271
0.008969063463715277
0.00896906346370462
0.00896906346370462
0.00896906346370462
0.00896906346375791
0.00896906346375791
0.00896906346375791
0.00924564330251421
0.013139440734619305
0.038718696749883624
0.036951131109373044
0.03871906889035728
1.122101790341677
17.36266761900473
29.22826922387327
33.242010307763834
27.94784117525895
13.943453443344644
0.3847523837524961
0.01019600753172865
0.008968492317839905
0.011958928581321908
0.011958554761395672
0.011958556440848693
0.008969063463743699
0.008969063463733041
0.008969063463733041
0.008969063463733041
0.008969063463729488
0.008969063463729488
0.008969063463729488
0.009245643302485788
0.013139440734590883
0.038718696749883624
0.036951131109373044
0.03871906889035728
9.621590734837325
16.091548539979918
29.811944034769
46.10659248125838
30.14391441786184
15.943622469314722
0.7541453400698401
0.01019600753172865
0.008968492317839905
0.011958928581321908
0.011958554761395672
0.011958556440848693
0.008969063463715277
0.00896906346370462
0.00896906346370462
0.00896906346370462
0.010569489126894031
0.010569489126894031
0.010569489126894031
0.010846068965650331
0.014739866397755423
0.014650083136251652
0.012882517495741066
0.01465045527672531
3.7288514917384505
19.83154170190617
34.67549674881549
40.220370504200474
33.42213724554929
18.62691825782144
1.9689997825026873
0.011796433194893187
0.010568917981004448
0.010569861267353035
0.0105694874474268
0.01056948912687982
0.01056948912687982
0.010569489126869162
0.010569489126869162
0.010569489126869162
0.010569489126894031
0.010569489126894031
0.010569489126894031
0.010846068965650331
0.014739866397755423
0.014650083136251652
0.012882517495741066
0.01465045527672531
2.5034257392523216
19.887325737735825
34.69223713461654
41.10964210368396
35.117053420303186
19.75170941566109
2.3463622674554223
0.011796433194893187
0.010568917981004448
0.010569861267353035
0.0105694874474268
0.01056948912687982
0.01056948912687982
0.010569489126869162
0.010569489126869162
0.010569489126869162
0.010569489126894031
0.010569489126894031
0.010569489126894031
0.010846068965650331
0.014739866397755423
0.014650083136251652
0.012882517495741066
0.01465045527672531
3.731617385659095
20.772566116304645
43.44339547771622
43.77188406027996
35.01727539318898
20.346172350834845
3.5240439061844944
0.011796433194893187
0.010568917981004448
0.010569861267353035
0.0105694874474268
0.01056948912687982
0.01056948912687982
0.010569489126869162
0.010569489126869162
0.010569489126869162
0.010569489126894031
0.010569489126894031
0.010569489126894031
0.010846068965650331
0.014739866397755423
0.014650083136251652
0.012882517495741066
0.01465045527672531
4.052420907522265
22.835626511585325
38.6354719787283
44.427837239629554
38.64184400021002
22.69979918753705
3.7064749191164967
0.011796433194893187
0.010568917981004448
0.010569861267353035
0.0105694874474268
0.01056948912687982
0.01056948912687982
0.010569489126869162
0.010569489126869162
0.010569489126869162
0.010569489126894031
0.010569489126894031
0.010569489126894031
0.010846068965650331
0.014739866397755423
0.014650083136251652
0.012882517495741066
0.01465045527672531
4.639049884770426
23.95645016911992
40.6623584891795
45.19134093398152
41.07530084034513
24.360368688415882
4.61687590256324
0.011796433194893187
0.010568917981004448
0.010569861267353035
0.0105694874474268
0.01056948912687982
0.01056948912687982
0.010569489126869162
0.010569489126869162
0.010569489126869162
0.010569489126894031
0.010569489126894031
0.010569489126894031
0.010846068965650331
0.014739866397755423
0.014650083136251652
0.012882517495741066
0.01465045527672531
5.205336613875334
25.199031038869396
41.40501065145243
47.04711343147494
41.66789731016448
41.34436218803236
5.1825080290247305
0.011796433194893187
0.010568917981004448
0.010569861267353035
0.0105694874474268
0.01056948912687982
0.01056948912687982
0.010569489126869162
0.010569489126869162
0.010569489126869162
0.010569489126908242
0.010569489126908242
0.010569489126908242
0.010846068965664542
0.014739866397769634
0.014650083136265863
0.012882517495755277
0.014650455276739522
5.74073697563071
27.080183491025398
42.63188445250625
49.269743979027005
42.545811386443816
26.74962656888916
12.008157183521528
0.011796433194907398
0.01056891798101866
0.010569861267367246
0.01056948744744101
0.010569489126894031
0.010569489126894031
0.010569489126883373
0.010569489126883373
0.010569489126883373
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
6.871642632678272
28.01892708841356
44.46036813512104
50.795823080645896
106.58255794649206
45.65362937564852
23.714312529835045
0.012346620258187176
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
7.741455512035956
30.0380980483313
45.54440833026531
52.381550518192654
46.09718575219168
32.50217756117802
16.587079821655994
0.012346620258187176
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
8.237102508350427
63.06435472204255
97.56398593909182
131.97354099173322
67.37458924459698
36.77946404788941
40.15532456838271
0.012346620258187176
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
12.05537832211375
43.822396524186736
49.316755983510156
160.0392304407297
94.84806385247161
55.33897229461793
22.30616600811813
0.012346620258187176
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
17.376461607566636
45.36069186380307
68.60933582840664
71.77667487245412
101.75651612551447
61.33702740154052
22.7770122341366
0.012346620258187176
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
24.539426452645213
120.70065034303185
175.42841942071286
178.86191938380105
164.0787456800404
70.11320347961875
26.805702269182845
0.012346373327859879
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015200642340019296
11.986707238743117
37.729326845649815
67.03308404535863
61.35040633998576
81.60951536913694
39.89416320822201
19.4395326086102
0.012346373327859879
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.011119676190202231
0.011119676190202231
0.011119676190202231
0.01139625602895853
0.015290053461063621
0.015200270199545637
0.013432704559035051
0.015197371137732027
29.178036532425825
72.93084161580785
100.10113117431632
97.42407743386734
56.327167829979366
57.587983628206075
19.69821972395479
0.01234664403987746
0.011119105044298437
0.011120048330647024
0.011119674510720788
0.01111967619017381
0.01111967619018802
0.011119676190177362
0.011119676190177362
0.011119676190177362
0.01111959748972232
0.01111959748972232
0.01111959748972232
0.01139617732847862
0.015290018695972815
0.015200235434454831
0.013432669793944245
0.015197382886705376
29.169658380038236
82.05966642830553
149.45697074115395
211.2869858810342
172.69330385266943
137.0687722774769
64.49784327289724
0.3878015172731905
0.011119026343818526
0.011119969630167557
0.011119595810240877
0.011119597489693898
0.01111959748970811
0.011119597489697451
0.011119597489697451
0.011119597489697451
0.01111959748972232
0.01111959748972232
0.01111959748972232
0.01139617732847862
0.015290018695972815
0.015200235434454831
0.013432669793944245
0.015200197441292437
16.02926389602048
41.01214048267306
60.23361890521778
77.32271324762088
61.34498720277391
51.82843517507299
26.125126526434787
0.011922951942621617
0.011119026343818526
0.011119969630167557
0.011119595810240877
0.011119597489693898
0.01111959748970811
0.011119597489697451
0.011119597489697451
0.011119597489697451
0.01111959748972232
0.01111959748972232
0.01111959748972232
0.01139617732847862
0.015290018695972815
0.015200235434454831
0.013432669793944245
0.015227293719655496
16.675144702362328
44.091508070110336
63.226172912301564
68.66288117721308
105.8737985182809
70.12194936255236
26.975348282497347
0.012892816438119195
0.011119026343818526
0.011119969630167557
0.011119595810240877
0.011119597489693898
0.01111959748970811
0.011119597489697451
0.011119597489697451
0.011119597489697451
0.01111959748972232
0.01111959748972232
0.01111959748972232
0.01139617732847862
0.015290018695972815
0.015200235434454831
0.013432669793944245
0.015378580594818966
17.47024912750624
42.05247590831623
64.77334567992143
68.7524200022902
61.17501353412357
46.51871490060978
22.254698974726626
0.06938213069128038
0.011119026343818526
0.011119969630167557
0.011119595810240877
0.011119597489693898
0.01111959748970811
0.011119597489697451
0.011119597489697451
0.011119597489697451
0.01111959748972232
0.01111959748972232
0.01111959748972232
0.01139617732847862
0.015290018695972815
0.015200235434454831
0.013432669793944245
1.5538912407312382
55.32888414563333
126.46766444677883
143.73513696759304
198.88450711914376
203.28618361383397
96.62166135669044
73.69551406496254
4.5959175216064265
0.011119026343818526
0.011119969630167557
0.011119595810240877
0.011119597489693898
0.01111959748970811
0.011119597489697451
0.011119597489697451
0.011119597489697451
0.011119597489718767
0.011119597489718767
0.011119597489718767
0.011396177328475067
0.015290018695969262
0.015200235434451278
0.013432669793940692
0.7614921169316714
22.08406507977047
48.371458243618434
67.03467697421085
75.03661984539164
132.86834405739828
53.405546010713756
24.17726823562588
1.1120486363511433
0.011119026343814974
0.011119969630164005
0.011119595810237325
0.011119597489690346
0.011119597489704557
0.011119597489693898
0.011119597489693898
0.011119597489693898
0.011119597489704557
0.011119597489704557
0.011119597489704557
0.011396177328460856
0.015290018695955051
0.015200235434437067
0.013432669793926481
1.5493095277156272
23.833183594313443
61.14689115151134
69.3155217889042
77.23419569125753
72.12681808440495
52.71393134622738
26.350088377430016
1.539892450761645
0.011119026343772341
0.011119969630121372
0.011119595810194692
0.011119597489647713
0.011119597489661924
0.011119597489679688
0.011119597489679688
0.011119597489679688
0.011119597489704557
0.011119597489704557
0.011119597489704557
0.011396177328460856
0.015290018695955051
0.015200235434437067
0.013432669793926481
1.120492078760083
29.210654240495405
50.61923895397225
158.3564428085954
94.71649888937807
68.38265888886804
51.715321284612386
69.46209195269134
5.701150170116077
0.011119026343772341
0.011119969630121372
0.011119595810194692
0.011119597489647713
0.011119597489661924
0.011119597489679688
0.011119597489679688
0.011119597489679688
0.011119597489704557
0.011119597489704557
0.011119597489704557
0.011396177328460856
0.015290018695955051
0.015200235434437067
0.013432669793926481
1.120492078760083
23.872266280084787

In [12]:
smhi_2026_pred_clipped = np.where(smhi_2026_pred < 0.1, 0, smhi_2026_pred)
for line in smhi_2026_pred_clipped:
    print(line)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.576952685432198
19.837195595526676
22.703866423956633
17.282033735281853
5.153803518554511
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.930737748713662
20.39503595022456
24.316548449494157
18.309821793088773
5.711390301944506
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.284191161698372
49.190324813145196
23.757311765485742
18.29462014331584
5.712658036756658
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.944825030758563
21.03137553630198
25.005071560263247
19.789579210263916
6.412915485710392
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.9629231273695928
31.912411455180738
54.01155814919518
28.64029044908672
46.08041926345013
7.866025895339253
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.7066589337398784
19.819549135686717
50.85390498631686
28.63984994844563
18.66885837045247
8.529947564870254
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.705972432338951
11.946734564955152
48.62790379255121
29.242952014281045
22.273055086994653
8.54466644027835
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.160082509122415
23.75396650979804
55.53092936273054
26.94200896835895
22.242478721422433
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12.492579377745534
29.124815025631587
68.46985169259635
50.742420359585054
10.116791420955561
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.1970946303472285
55.71968289906522
100.02527235161422
114.27215914705988
86.37039615559827
38.672566733597336
1.1121595663540051
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.044155116650709
51.86193291523041
89.49325368680387
65.3800050524821
48.49270462099411
15.931169577230124
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.7306422732493645
45.265882899581044
96.39223933725452
112.03359996523672
54.79536614249277
14.252390855470756
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.30179823567356584
13.960258836403076
27.145765372995278
31.820913587656367
26.469460031472845
12.406619128247806
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.3899970231936503
13.965873595612724
27.89749480303761
32.505192871398954
27.180862373603567
12.472389881201918
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.24959552013838
29.582077477868832
29.61805641163585
33.44882128676707
29.196225203801248
13.46315119113347
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.7605835758546529
14.510779779623158
27.97116456278581
32.0849161686132
26.99420140183115
13.46315119113347
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.122101790341677
17.36266761900473
29.22826922387327
33.242010307763834
27.94784117525895
13.943453443344644
0.3847523837524961
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.621590734837325
16.091548539979918
29.811944034769
46.10659248125838
30.14391441786184
15.943622469314722
0.7541453400698401
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.7288514917384505
19.83154170190617
34.67549674881549
40.220370504200474
33.42213724554929
18.62691825782144
1.9689997825026873
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.5034257392523216
19.887325737735825
34.69223713461654
41.10964210368396
35.117053420303186
19.75170941566109
2.3463622674554223
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.731617385659095
20.772566116304645
43.44339547771622
43.77188406027996
35.01727539318898
20.346172350834845
3.5240439061844944
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.052420907522265
22.835626511585325
38.6354719787283
44.427837239629554
38.64184400021002
22.69979918753705
3.7064749191164967
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.639049884770426
23.95645016911992
40.6623584891795
45.19134093398152
41.07530084034513
24.360368688415882
4.61687590256324
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.205336613875334
25.199031038869396
41.40501065145243
47.04711343147494
41.66789731016448
41.34436218803236
5.1825080290247305
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.74073697563071
27.080183491025398
42.63188445250625
49.269743979027005
42.545811386443816
26.74962656888916
12.008157183521528
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6.871642632678272
28.01892708841356
44.46036813512104
50.795823080645896
106.58255794649206
45.65362937564852
23.714312529835045
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
7.741455512035956
30.0380980483313
45.54440833026531
52.381550518192654
46.09718575219168
32.50217756117802
16.587079821655994
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.237102508350427
63.06435472204255
97.56398593909182
131.97354099173322
67.37458924459698
36.77946404788941
40.15532456838271
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12.05537832211375
43.822396524186736
49.316755983510156
160.0392304407297
94.84806385247161
55.33897229461793
22.30616600811813
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
17.376461607566636
45.36069186380307
68.60933582840664
71.77667487245412
101.75651612551447
61.33702740154052
22.7770122341366
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
24.539426452645213
120.70065034303185
175.42841942071286
178.86191938380105
164.0787456800404
70.11320347961875
26.805702269182845
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.986707238743117
37.729326845649815
67.03308404535863
61.35040633998576
81.60951536913694
39.89416320822201
19.4395326086102
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
29.178036532425825
72.93084161580785
100.10113117431632
97.42407743386734
56.327167829979366
57.587983628206075
19.69821972395479
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
29.169658380038236
82.05966642830553
149.45697074115395
211.2869858810342
172.69330385266943
137.0687722774769
64.49784327289724
0.3878015172731905
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
16.02926389602048
41.01214048267306
60.23361890521778
77.32271324762088
61.34498720277391
51.82843517507299
26.125126526434787
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
16.675144702362328
44.091508070110336
63.226172912301564
68.66288117721308
105.8737985182809
70.12194936255236
26.975348282497347
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
17.47024912750624
42.05247590831623
64.77334567992143
68.7524200022902
61.17501353412357
46.51871490060978
22.254698974726626
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.5538912407312382
55.32888414563333
126.46766444677883
143.73513696759304
198.88450711914376
203.28618361383397
96.62166135669044
73.69551406496254
4.5959175216064265
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.7614921169316714
22.08406507977047
48.371458243618434
67.03467697421085
75.03661984539164
132.86834405739828
53.405546010713756
24.17726823562588
1.1120486363511433
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.5493095277156272
23.833183594313443
61.14689115151134
69.3155217889042
77.23419569125753
72.12681808440495
52.71393134622738
26.350088377430016
1.539892450761645
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.120492078760083
29.210654240495405
50.61923895397225
158.3564428085954
94.71649888937807
68.38265888886804
51.715321284612386
69.46209195269134
5.701150170116077
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.120492078760083
23.872266280084787
56.19943109813746
68.53676486880676
79.16883581212055
71.52964564791277
68.09859007464847
31.572451237436976
2.483403437432522
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.9763549239502896
28.1908310160089
88.73120452913197
220.4994166048601
172.55599811358414
75.24686659049118
57.19881640883764
44.69240964168918
3.679708427655345
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.176027740008612
81.24976666226057
112.66947061786232
93.89912610010943
157.77758608695459
112.48775431024383
71.47223027623481
34.67452986809721
4.596473801379218
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
20.43516971619065
111.78232105897833
200.29392904086956
258.36826450765335
278.04098731714544
262.5842614299897
204.96678856189376
119.6910502423479
27.372785683820762
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
23.70578384245505
114.37283444701421
205.029700395489
262.9260273524711
277.84945139341426
263.25237118933876
187.04237557271335
76.7548070307738
22.6004721919699
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
24.26941104986973
105.48749792143306
187.06414281474363
250.467375826499
270.46946408580555
237.67787486179617
204.3691851678074
104.86382249659877
21.831690922068052
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6.7329671453194075
37.448139274428804
65.99194137222682
152.2799107086951
271.2367888985664
212.82647228075461
164.78876581443794
98.1846072820526
26.512639669892373
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
26.0832762589726
92.8134754369216
109.22222493093489
225.0303118348229
156.79074489177904
87.62780482045717
190.8757568367877
40.92680674924364
11.112773103684612
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
35.365478140867005
125.60255826266757
74.30513141311442
152.63386393611313
273.1058220992854
204.27089375697497
72.14353108190615
139.89880646496417
45.33755928239336
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
42.85907152386573
119.67241024717924
213.75039895403052
205.56878127548057
223.15344642876028
238.91754808217192
181.3150605695215
137.2790619261938
28.510271201616444
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.58124650770489
40.81499711605118
71.87266219523055
88.15220868113873
96.91840714715944
88.01936854137361
69.8107928639921
41.684982575591285
11.968025022165422
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
55.345682642048246
153.53703676516668
250.9395229679894
300.41227101824416
318.88439025658954
280.25161816129963
239.64533286023118
149.84767260950503
47.67160777847907
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
13.369029346589262
44.72178617749707
88.43271562232927
94.559493291624
103.68988212554456
96.53508780030961
77.03067223455953
48.44095740542599
15.726762773896457
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
15.722972044051525
49.38555602474365
79.41723450745963
98.68793333644416
106.3624044714295
98.71188020003954
80.29291433248272
52.038152984767166
18.254828319732088
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
34.28989136848539
52.35143163919523
83.38851751656122
111.67977918811286
104.82753232047878
97.89062820439544
78.65599064373409
48.59049517662228
16.3194114099074
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
20.295774299298493
54.45445896414743
91.21543674450633
106.82726845588365
111.30273383249718
111.23550006334207
86.97033013047381
57.01487441307622
22.171321187186997
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.580249478062699
94.81348845066682
198.65688478460135
283.97917803046664
342.39289333513227
361.88795936520785
339.97099948568797
285.72114307583524
196.05361880304437
85.67773673159118
5.156008688197789
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
23.36219378833958
161.94366107855612
273.32653895207545
296.3573535860988
345.17449024951554
288.5118155923352
226.11199460361516
78.29478758998398
54.953011107300284
7.428698717005354
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.877536444809461
106.57341784797023
211.50322571661474
303.5029573250698
357.53136451143513
371.46230162731916
355.74086354225824
297.7759236174562
210.27124189560217
104.24124937502023
10.025014348177931
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.852355797262083
107.8650033383861
211.3022803386591
295.7727472824823
347.4285254426816
357.67313988595515
338.5972566730463
292.7883802956743
197.22286061743822
77.51210784658001
6.583803887340362
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
13.698345243823248
107.88309394139037
211.08623921278428
301.9075799825853
357.0596893872136
372.133023957471
355.7737569462135
298.63670054213213
210.70679817999417
105.91754720652955
13.57267982031178
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.5365784653038055
24.604447073276148
60.358987100688395
210.3956224182902
104.48514991241507
130.51247036582083
107.92026082400226
149.2799204884986
61.14707191308114
28.077332860996258
1.9294014499742882
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
20.139752651655638
116.901503632438
219.95707066593775
309.09186989240646
358.3442183552493
370.5596407753994
354.3125618964732
291.62802747695713
206.1411017297722
105.27677344412763
16.448773437882178
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.000364493736664
37.65363549094078
71.62221416296815
319.36849263617256
373.1342584336728
377.09765082174385
370.57711581023324
313.85283794635427
232.20051988098686
122.09138824937034
18.76451139249486
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
24.546388945485457
122.13157891225167
230.26378228893964
317.5597188058417
369.4921482927641
386.3986905824927
366.7216670814096
309.5022948900708
218.42485551167968
112.98044527926898
21.003810706646227
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.6143652287160295
34.90922599233293
71.55113376438119
144.65041850021092
118.40284268609564
128.6975555113372
124.74896009122584
102.17587217098824
71.52403501785243
35.62899884984976
5.584967407910741
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.010239382589907
75.92638429135823
82.38183672760223
170.3274612128978
401.62176844258784
411.74419370804793
348.23755490069294
301.3847059816642
218.394034285137
129.9618976101308
25.55710528940953
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
25.844903707467246
113.57534663090692
172.80891789534792
265.16904105436055
253.46193492952762
358.68456951510933
344.85409732235144
209.3983872557373
169.3568734596996
59.553512692424185
7.063789289455491
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.073031292880062
45.596506483656476
82.0541671219944
109.3495284795328
128.1968476774979
132.15665257228042
128.1641932876963
105.39029739472613
77.51524426906494
40.40342788953473
8.69367612415024
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.796497336852033
63.441298579326514
82.81181186103122
115.94831385149735
132.1204515473133
138.54491357950306
163.6278388432335
110.82476484264699
82.20454666719002
43.40196867695712
10.604564630589202
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
59.30238285882546
166.5748410918643
247.24847485793626
342.40449053192003
339.0005809767092
431.66107753715687
382.3046108241496
337.58912175909427
86.00149445290245
81.98957025402218
11.690789530500503
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
16.05103552401975
53.65767251900875
93.58759295097107
202.49673510258577
266.38934375807844
241.29656743042406
383.8676610227507
375.2278983218599
279.9629760531527
142.48439711761293
47.869537466303306
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
53.092379079669634
132.6553348573145
273.51733854633227
324.34735130748874
419.7003306036922
434.16438326896935
413.3018310052747
188.83572431810356
90.17152723230222
50.017394718029884
22.32803827265294
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
15.970807821986536
50.47804487358838
86.24084243969224
117.30851902015775
137.94795729296823
185.84204036602296
244.44815448466161
127.90116019360296
274.9291674248675
168.72922099476298
57.775714096483085
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.2927529816461476
79.20179961000231
193.975185455354
297.21229259998336
321.80568220688554
190.00467473951332
199.71503281199008
337.1071168722119
365.11113361652883
255.8680281034549
173.61807293642374
59.83349662199592
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.4332666022919105
82.13973734077982
199.8365074306419
307.7789255295183
396.33916006810927
442.7875754458319
458.63456104532946
435.9548723440376
367.56304284042074
216.93755920769638
157.36447574518243
56.246149937933225
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.550265377540271
81.68435225964738
199.8468026905369
308.4965655488559
369.2121570613164
427.24765908499853
463.55634391400304
454.3967202053599
395.6416937994498
270.09719136877874
151.74518159529524
70.15415146233198
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.962489088440412
61.87591806669976
173.46806102267584
228.6642045212372
134.19014341390638
157.3084932980959
155.35027730014986
149.2881261856258
382.0587740303837
303.8912583687806
192.00771760448453
73.38784563388715
0.270245581101398
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.984039423550807
89.880437329242
197.13567273013146
221.3031541728193
196.81158856249644
188.39162588770589
154.0248811954561
144.8755213999305
207.89319929507968
93.50241464897786
54.75814794303099
19.141488594283718
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.5085424299041034
23.393795913934138
83.99766184526081
194.35100008107347
138.78975141746923
147.98583170732755
156.36912513202608
150.00073794302256
131.76660358832117
102.70375242274469
72.153875290414
55.07236695327845
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.755788106015038
34.431999328722576
79.80492875236872
153.17648480047401
164.63849761897762
164.3292229373244
244.54067790560347
218.94493171225562
181.52775975422
163.96499073374338
78.2442436231556
25.10837974760129
3.2255008572000072
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
19.386739801569345
124.67389951229408
256.32691262479983
370.2441205178933
454.28465875195445
500.3845820032248
509.91296708545366
486.8956816655207
434.04187208554384
335.67686329344855
211.11514395743765
85.36897060287225
5.182441919302075
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
19.373254774189945
57.351378568978724
112.18026772102353
111.31731273947467
145.67969510553135
164.58719055208695
170.3066572261457
163.12140179621474
139.33690426553855
103.761798652945
64.36905228666414
26.231839452991476
0.13128342686205677
0.0
0.0
0.0
0.0
0.0
0.0
0.14097494038247382
0.14097494038247382
0.14097494038247382
0.1767603323821481
0.1784818366506643
14.90633018023254
124.92691649410774
253.43779157033694
350.38517695544596
436.96926975539077
426.5242019610806
328.5384168926582
176.69091040941743
293.1916319449432
347.03975846860374
223.9251552507182
92.44612441715971
7.731553476597437
0.145060616748014
0.11118873169031408
0.10982983304617298
0.14097488899623917
0.14097488899623917
0.14097494038244895
0.0
0.0
0.0
0.12096008248064491
0.122681586749161
5.545898509118264
48.033893105542525
171.58094740589132
237.26111383314438
372.2627593637209
173.8535970211381
223.8036791353307
167.11034990993193
144.47124936908986
108.31642943143609
69.87739302967977
28.119988990862602
1.6292929379983334
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
7.304961111237975
53.20150114521472
96.21555072045246
170.71099639237397
442.717907623895
428.78248520168427
511.2814130013684
486.97983169967006
427.9787275684446
350.2110084312371
239.1798469202603
98.07224539464428
13.393735919877237
0.0
0.0
0.0
0.0
0.0
0.0
0.32655141251479397
0.32655141251479397
0.32655141251479397
0.2870981173287335

In [13]:
smhi_2026_time = raw_smhi_2026['datetime'].copy()
type(smhi_2026_time)

pandas.Series

In [14]:
result = pd.DataFrame({
    'time': smhi_2026_time,
    'predicted_pv_output': smhi_2026_pred_clipped
})
print(result)

                    time  predicted_pv_output
0    2026-01-01 00:00:00             0.000000
1    2026-01-01 01:00:00             0.000000
2    2026-01-01 02:00:00             0.000000
3    2026-01-01 03:00:00             0.000000
4    2026-01-01 04:00:00             0.000000
...                  ...                  ...
3619 2026-05-31 19:00:00            15.581469
3620 2026-05-31 20:00:00             0.000000
3621 2026-05-31 21:00:00             0.000000
3622 2026-05-31 22:00:00             0.000000
3623 2026-05-31 23:00:00             0.000000

[3624 rows x 2 columns]

In [15]:
result.to_csv("smhi_2026_predicted_pv_output_with_time.csv", index=False)